-- MySQL Script generated by MySQL Workbench
-- Fri 02 Apr 2021 04:49:06 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`guests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`guests` ;

CREATE TABLE IF NOT EXISTS `mydb`.`guests` (
  `guestID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`guestID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reservations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reservations` (
  `reservationID` INT NOT NULL,
  `guestID` INT NOT NULL,
  `roomID` INT NOT NULL,
  `invoice` INT NOT NULL,
  `check_in` DATETIME NOT NULL,
  `check_out` DATETIME NULL,
  `party_size` INT NULL,
  PRIMARY KEY (`reservationID`),
  INDEX `guestID_fk_idx` (`guestID` ASC) VISIBLE,
  INDEX `roomID_fk_idx` (`roomID` ASC) VISIBLE,
  CONSTRAINT `guestID_fk`
    FOREIGN KEY (`guestID`)
    REFERENCES `mydb`.`guests` (`guestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roomID_fk`
    FOREIGN KEY (`roomID`)
    REFERENCES `mydb`.`rooms` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `roomID` INT NOT NULL,
  `room_number` INT NOT NULL,
  `floor_number` INT NOT NULL,
  PRIMARY KEY (`roomID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`room_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`room_type` (
  `typeID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `base_price` DECIMAL(15,2) NOT NULL,
  `description` VARCHAR(255) NULL,
  `max_occupancy` INT NULL,
  `typeID` VARCHAR(45) NULL,
  PRIMARY KEY (`typeID`),
  CONSTRAINT `typeID_fk`
    FOREIGN KEY ()
    REFERENCES `mydb`.`rooms` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
